name: zpevnik

publish_to: 'none'

version: 3.2.1+184

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  proscholy_common:
    git: https://github.com/glowspace/proscholy-phone-common.git

  sqflite: ^2.0.2+1
  firebase_core: ^3.10.1
  flutter_riverpod: ^3.0.0
  package_info_plus: ^9.0.0
  path: ^1.9.1
  sentry_flutter: ^9.6.0
  shared_preferences: ^2.4.0
  flutter_quill: ^11.0.0
  flutter_native_splash: ^2.4.6
  firebase_analytics: ^11.6.0

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # fonts must be defined per project, otherwise they are not bundled
  fonts:
    - family: CustomIcon
      fonts:
        - asset: packages/proscholy_common/assets/fonts/CustomIcon.ttf
    - family: KaiseiHarunoUmi
      fonts:
        - asset: packages/proscholy_common/assets/fonts/KaiseiHarunoUmi-Regular.ttf
    - family: Amiri
      fonts:
        - asset: packages/proscholy_common/assets/fonts/Amiri-Regular.ttf

  assets:
    - assets/data.json
    - assets/svg.zip
    - assets/images/logos/
