// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnU4_dIWi6H_gSa-8ZbSd5zHTmIUmPoX0',
    appId: '1:1053312555544:android:d5af5b8eae512622f1c16d',
    messagingSenderId: '1053312555544',
    projectId: 'proscholycz',
    databaseURL: 'https://proscholycz.firebaseio.com',
    storageBucket: 'proscholycz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6nG_9TVDdKTgv5NmkK4Mc4mk58ZBjihI',
    appId: '1:1053312555544:ios:e5370d3eba3dc0a3f1c16d',
    messagingSenderId: '1053312555544',
    projectId: 'proscholycz',
    databaseURL: 'https://proscholycz.firebaseio.com',
    storageBucket: 'proscholycz.appspot.com',
    iosClientId: '1053312555544-rubd9dm06da6qqv3dppg5ht7cqfrqqbp.apps.googleusercontent.com',
    iosBundleId: 'cz.proscholy.id.Zpevnik',
  );
}
